version: '2.1'
services:
  core:
    image: "danuk/shm:latest"
    restart: always
    environment:
      TZ: ${TZ}
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASS: ${MYSQL_PASS}
      DB_HOST: mysql
      DB_PORT: 3306
    ports:
      - "8080:80"
    depends_on:
      mysql:
        condition: service_healthy
  spool:
    image: "danuk/shm:latest"
    restart: always
    environment:
      TZ: ${TZ}
      SHM_ROLE: "spool"
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASS: ${MYSQL_PASS}
      DB_HOST: mysql
      DB_PORT: 3306
    depends_on:
      mysql:
        condition: service_healthy
  admin:
    image: "danuk/shm-admin:latest"
    restart: always
    environment:
      SHM_URL: http://core
    ports:
      - "8081:80"
  client:
    image: "danuk/shm-client:latest"
    restart: always
    environment:
      SHM_URL: http://core
    ports:
      - "8082:80"
  mysql:
    platform: linux/amd64
    image: "mysql:5.7"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: ${TZ}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASS}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASS}
    volumes:
      - "mysql-data:/var/lib/mysql"
    ports:
      - "3306:3306"
    healthcheck:
      test: "mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD"
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  mysql-data:
    driver: local

