apiVersion: v1
entries:
  shm:
  - apiVersion: v2
    created: "2023-04-26T22:01:36.14185+03:00"
    dependencies:
    - name: helm-common
      repository: file://charts/helm-common
      version: 0.2.12
    - name: mysql
      repository: https://charts.bitnami.com/bitnami
      version: 9.7.2
    description: A Helm chart for Kubernetes
    digest: fea24e4c50cea10a8b16519d18fc5c55913f06561aa5e46c6f99f9e7b8a05c37
    home: https://github.com/danuk/shm
    maintainers:
    - email: danek1982@gmail.com
      name: danuk
    name: shm
    type: application
    urls:
    - https://danuk.github.io/shm/shm-0.0.1.tgz
    version: 0.0.1
generated: "2023-04-26T22:01:36.13907+03:00"
